//--- Common
#define COLOUR_LOGIBOX_LIMITREACHED_R 0.627
#define COLOUR_LOGIBOX_LIMITREACHED_G 0.243
#define COLOUR_LOGIBOX_LIMITREACHED_B 0.067
#define COLOUR_LOGIBOX_LIMITREACHED_RGBA ARR_4(COLOUR_LOGIBOX_LIMITREACHED_R,COLOUR_LOGIBOX_LIMITREACHED_G,COLOUR_LOGIBOX_LIMITREACHED_B,1)

#define COLOUR_LOGIBOX_GREEN_R 0.041
#define COLOUR_LOGIBOX_GREEN_G 0.956
#define COLOUR_LOGIBOX_GREEN_B 0.007
#define COLOUR_LOGIBOX_GREEN_RGBA ARR_4(COLOUR_LOGIBOX_GREEN_R,COLOUR_LOGIBOX_GREEN_G,COLOUR_LOGIBOX_GREEN_B,1)

#define COLOUR_LOGIBOX_YELLOW_R 1
#define COLOUR_LOGIBOX_YELLOW_G 0.871
#define COLOUR_LOGIBOX_YELLOW_B 0.014
#define COLOUR_LOGIBOX_YELLOW_RGBA ARR_4(COLOUR_LOGIBOX_YELLOW_R,COLOUR_LOGIBOX_YELLOW_G,COLOUR_LOGIBOX_YELLOW_B,1)

#define COLOUR_LOGIBOX_RED_R 1
#define COLOUR_LOGIBOX_RED_G 0.095
#define COLOUR_LOGIBOX_RED_B 0.033
#define COLOUR_LOGIBOX_RED_RGBA ARR_4(COLOUR_LOGIBOX_RED_R,COLOUR_LOGIBOX_RED_G,COLOUR_LOGIBOX_RED_B,1)

//--- IDD/IDCs
#define IDD_RSCMTILOGIMENU_AIRCRAFT 78401
#define IDD_RSCMTILOGIMENU_VEHICLE  78402
#define IDD_RSCMTILOGIBOX_SCREEN    78403

#define IDC_RSCMTILOGIMENU_TITLE		                    9969
#define IDC_RSCMTILOGIMENU_TEXTSELECTVEHICLE		        9970
#define IDC_RSCMTILOGIMENU_TEXTSELECTSKIN		            9971
#define IDC_RSCMTILOGIMENU_TEXTOPERATIONPROGRESS		    9972
#define IDC_RSCMTILOGIMENU_TEXTOPERATIONBLOCKED 		    9982
#define IDC_RSCMTILOGIMENU_TEXTLOGIBOXSTATUS		        9973
#define IDC_RSCMTILOGIMENU_TEXTOUTPUTAREA		            9974
#define IDC_RSCMTILOGIMENU_TEXTASSETLIMIT		            9975
#define IDC_RSCMTILOGIMENU_TEXTCONFIGURELOADOUT		        9976
#define IDC_RSCMTILOGIMENU_TEXTASSETLIMITEDIT		        9977
#define IDC_RSCMTILOGIMENU_TEXTLOGIBOXSTATUSEDIT		    9978
#define IDC_RSCMTILOGIMENU_TEXTOUTPUTAREAEDIT		        9979
#define IDC_RSCMTILOGIMENU_BACKGROUND		                10169
#define IDC_RSCMTILOGIMENU_PICTUREVEHICLEPREVIEW		    10170
#define IDC_RSCMTILOGIMENU_LISTBOXVEHICLE		            10469
#define IDC_RSCMTILOGIMENU_LISTBOXSKIN		                10470
#define IDC_RSCMTILOGIMENU_PROGRESSOPERATIONPROGRESS		10869
#define IDC_RSCMTILOGIMENU_CHECKBOXCONFIGURELOADOUTEDIT		11769
#define IDC_RSCMTILOGIMENU_BUTTONOK                         11770
#define IDC_RSCMTILOGIMENU_BUTTONCANCEL                     11771
#define IDC_RSCMTILOGIBOX_SCREEN_BACKGROUND                 12769
#define IDC_RSCMTILOGIBOX_SCREEN_TITLE                      12780
#define IDC_RSCMTILOGIBOX_SCREEN_TEXTLOGIBOXSTATUS          12781
#define IDC_RSCMTILOGIBOX_SCREEN_TEXTSPAWNING               12782
#define IDC_RSCMTILOGIBOX_SCREEN_TEXTLOGIBOXSTATUSEDIT      12783
#define IDC_RSCMTILOGIBOX_SCREEN_TEXTSPAWNINGEDIT           12734
